### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by riteshsonawane1372** [HubGenixx/BangTigada#13]
Below is an example
<footer>
  <div class="footer-container">
    <div class="footer-left">
      <h3>About Us</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac commodo libero. Donec scelerisque, eros eget ullamcorper fringilla, odio magna accumsan sapien, at mollis mauris dolor a orci. </p>
    </div>
    <div class="footer-middle">
      <h3>Latest Posts</h3>
      <ul>
        <li><a href="#">Post Title 1</a></li>
        <li><a href="#">Post Title 2</a></li>
        <li><a href="#">Post Title 3</a></li>
        <li><a href="#">Post Title 4</a></li>
      </ul>
    </div>
    <div class="footer-right">
      <h3>Contact Us</h3>
      <p>123 Main Street<br>Anytown, USA 12345<br>Email: info@example.com<br>Phone: 555-555-5555</p>
    </div>
  </div>
  <div class="footer-bottom">
    <p>&copy; 2023 Your Website Name | Made by BangTigada</p>
  </div>
</footer>

**Comment by adityasimant** [comment]
I am working on this issue.
